config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  scope module: :web do
    root to: 'home#index'

    resource :sessions, only: [:new, :create, :destroy]
    resource :registrations, only: [:new, :create]
    resources :teams, only: [:index, :show] do
      scope module: :teams do
        resources :channels, only: [:index, :show, :new, :create]
        resource :join, only: [:create]
      end
    end

    resources :channels, only: [] do
      scope module: :channels do
        resource :join, only: [:create]
      end
    end

    namespace :account do
      resources :teams, only: [:index, :new, :create]
      resources :notifications
      resource :users, only: [:edit, :update, :destroy, :show]
    end
  end

  scope module: :api do
    resources :channels, only: [] do
      scope module: :channels do
        resources :messages, only: [:create, :update, :destroy]
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include UserOnboarding
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :first_name, :last_name, presence: true
  validates :password, presence: true, on: :create

  has_many :team_invitations, dependent: :destroy
  has_many :teams, through: :team_invitations
  has_many :channel_invitations, dependent: :destroy
  has_many :channels, through: :channel_invitations
  has_many :owned_teams,
           foreign_key: :owner_id,
           class_name: 'Team',
           dependent: :destroy,
           inverse_of: :owner
  has_many :notifications, dependent: :destroy
  has_many :messages, dependent: :destroy, class_name: 'Team::Channel::Message'
  has_one_attached :avatar

  def guest?
    false
  end
  
  def find_team(id)
    teams.friendly.find(id)
  end

  def all_teams
    (teams + owned_teams).uniq
  end

  def member_of_team?(team)
    teams.include?(team)
  end

  def to_s
    first_name
  end
end

app/controllers/web/account/application_controller.rb
class Web::Account::ApplicationController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/web/account/notifications_controller.rb
class Web::Account::NotificationsController < Web::Account::ApplicationController
  def index
    @notifications = current_user.notifications
  end
end

app/controllers/web/account/teams_controller.rb
class Web::Account::TeamsController < Web::Account::ApplicationController
  def index
    @teams = current_user.all_teams
  end

  def new
    @team = Team.new
  end

  def create
    @team = TeamMutator.create(team_params, current_user)

    if @team.persisted?
      redirect_to account_teams_path, notice: "Team is created"
    else
      render :new, notice: "Something went wrong"
    end
  end

  private

  def team_params
    params.require(:team).permit(:name, :description)
  end
end

app/controllers/web/account/users_controller.rb
class Web::Account::UsersController < Web::Account::ApplicationController
  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update(user_params)
      redirect_to edit_account_users_path, notice: "User is updated"
    else
      redirect_to edit_account_users_path, alert: "Something went wrong"
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :avatar)
  end
end

app/views/web/account/users/edit.html.slim
.container
  .row
    .col-lg-6.col-md-6.ml-auto.mr-auto
      h2.text-center Account
      = simple_form_for @user, url: account_users_path do |f|
       = f.input :first_name
       = f.input :last_name
       = f.file_field :avatar, class: 'form-group', direct_upload: true
       = f.submit 'Save', class: 'btn btn-primary'
    - if @user.should_see_onboarding?
      .col-lg-4.col-md-4
        h2.text-centre Onboarding
        .progress.mb-3
          .progress-bar role="progressbar" style="width:  #{@user.onboarding_percent}%" aria-valuenow="#{@user.onboarding_percent}" aria-valuemax="100"
        .
          = onboarding_step_icon(@user.has_team?)
          span Join the team
        .
          = onboarding_step_icon(@user.has_message?)
          span Write a message
        .
          = onboarding_step_icon(@user.has_avatar?)
          span Add avatar